kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-ui
  labels:
    app: frontend-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-ui
  template:
    metadata:
      labels:
        app: frontend-ui
    spec:
      containers:
      - name: greet
        image: docker.io/sujoysett/engagement-tracker-frontend-ui:v1
        imagePullPolicy: Always
        ports:
          - containerPort: 8091
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-ui-service
spec:
  selector:
    app: frontend-ui
  ports:
    - port: 80
      targetPort: 8091
  type: LoadBalancer
